version: "3"
services:
  manager:
    build: .
    depends_on:
      - database
    environment:
      CSV_FILENAME: data.csv
      POSTGRES_USER: ines
      POSTGRES_PASSWORD: password
      POSTGRES_DB: POSTGRES_DB
  database:
    image: postgres
    environment:
      CSV_FILENAME: data.csv
      POSTGRES_USER: ines
      POSTGRES_PASSWORD: password
      POSTGRES_DB: POSTGRES_DB

